/**
 * BCA STORE - MS-DOS Knowledge Base
 * Training dataset for the AI Assistant.
 */

const MS_DOS_KNOWLEDGE = {
  // MS-DOS Basics
  "what is ms-dos": "Microsoft Disk Operating System (MS-DOS) is a non-graphical command-line operating system derived from 86-DOS.",
  "who developed ms-dos": "Microsoft Corporation developed MS-DOS, originally released in 1981.",
  "what type of os is dos": "It is a single-user, single-tasking, command-line interface (CLI) operating system.",
  "full form of dos": "Disk Operating System.",
  "purpose of ms-dos": "Managing system resources, files, and running programs via text commands.",
  "command prompt": "The interface in MS-DOS where users type commands, typically represented by C:\\>.",
  "internal vs external commands": "Internal commands are built into COMMAND.COM and reside in RAM (e.g., DIR, CLS). External commands are separate files on the disk (e.g., FORMAT, XCOPY).",
  "booting process in dos": "Starting the computer and loading DOS system files (IO.SYS, MSDOS.SYS, COMMAND.COM) into memory.",
  "root directory": "The top-most directory in a disk's hierarchy, indicated by a backslash (\\).",
  "file and filename": "A file is a collection of data. A DOS filename typically follows the 8.3 format (8 characters for name, 3 for extension).",
  "path in dos": "The route or address leading to a specific file or directory (e.g., C:\\WINDOWS\\SYSTEM).",

  // Basic DOS Commands
  "dir command": "Displays a list of files and subdirectories in the current directory.",
  "cls command": "Clears the command prompt screen.",
  "date and time commands": "Used to display or change the current system date and time.",
  "ver command": "Displays the current version of the MS-DOS operating system.",
  "vol command": "Displays the disk volume label and serial number.",
  "copy command": "Used to copy one or more files from one location to another.",
  "del and erase commands": "Used to delete specified files from the disk.",
  "ren command": "Renames a file or a set of files.",
  "type command": "Displays the content of a text file on the screen.",
  "md or mkdir": "Creates a new directory (folder).",
  "rd or rmdir": "Removes an empty directory.",
  "cd or chdir": "Changes the current working directory or displays the current path.",
  "tree command": "Graphically displays the directory structure of a drive or path.",
  "move command": "Moves files and renames directories.",
  "exit command": "Closes the DOS command interpreter (COMMAND.COM).",

  // File & Disk Management
  "attrib command": "Displays or changes file attributes like Read-only, Archive, Hidden, and System.",
  "xcopy command": "An advanced version of COPY that can copy entire directory trees and subdirectories.",
  "fc command": "File Compare; compares two files and displays the differences between them.",
  "format command": "Prepares a disk for use by creating a new file system and deleting existing data.",
  "chkdsk command": "Checks a disk for errors and displays a status report of the disk and memory.",
  "scandisk": "A utility that finds and repairs disk errors, a more advanced version of CHKDSK.",
  "defrag command": "Optimizes disk performance by rearranging fragmented files into contiguous blocks.",
  "backup and restore": "Commands used to create and recover safety copies of files in case of data loss.",

  // Batch Files & System Configuration
  "batch file": "A text file containing a series of DOS commands that are executed sequentially (.BAT extension).",
  "autoexec.bat": "A special batch file that runs automatically every time the system starts up.",
  "config.sys": "A system configuration file used to load device drivers and set system parameters during boot.",
  "echo command": "Used in batch files to display messages or turn command echoing on/off.",
  "pause command": "Suspends the processing of a batch program and displays a 'Press any key to continue' message.",
  "rem command": "Used to add comments (remarks) in a batch file which are ignored by DOS.",
  "goto and labels": "Used in batch files to jump to a specific section identified by a label (starting with :).",

  // Important Terms & Files
  "wildcards in dos": "Special characters (* and ?) used for pattern matching. * replaces multiple characters, ? replaces one.",
  "command.com": "The primary DOS command interpreter responsible for processing user input.",
  "io.sys and msdos.sys": "Hidden system files required for booting DOS and managing hardware/software interaction.",
  "boot sector": "The first sector of a disk that contains the code necessary to start the OS loading process.",
  "himem.sys": "An external driver that manages extended memory (XMS) above the 1MB limit.",
  "conventional memory": "The first 640 KB of memory in a PC where DOS and applications primarily run.",

  // Advanced Logic
  "redirection operators": "Used to change the source/destination of data: > (output), >> (append), < (input).",
  "pipe operator |": "Directs the output of one command to be used as the input for another (e.g., DIR | MORE).",
  "is dos multitasking": "No, MS-DOS is a single-tasking OS, meaning it can only run one program at a time.",
  "shell in dos": "The user interface that interprets commands, usually COMMAND.COM.",
  "kernel in dos": "The core part of the OS that manages files and hardware (MSDOS.SYS).",

  // Troubleshooting
  "ctrl+c and ctrl+break": "Used to stop or interrupt a running DOS command or process.",
  "invalid command error": "Occurs when DOS cannot find an internal or external command with the name entered.",
  "bad command or file name": "The default error message when DOS doesn't recognize a command or cannot find the file.",

  // 150 MS-DOS One-Word Terms
  "dos": "Disk Operating System.",
  "ms-dos": "Microsoft Disk Operating System.",
  "dir": "Used to display directory contents and files.",
  "cls": "Used to clear the screen.",
  "date": "Displays or changes the system date.",
  "time": "Displays or changes the system time.",
  "ver": "Shows the current MS-DOS version.",
  "vol": "Displays the volume label of the disk.",
  "copy": "Used to copy files from one location to another.",
  "del": "Used to delete files.",
  "erase": "A synonym for the DEL command, used to delete files.",
  "ren": "Used to rename a file.",
  "type": "Displays the content of a text file.",
  "md": "Make Directory; creates a new folder.",
  "rd": "Remove Directory; deletes an empty folder.",
  "cd": "Change Directory; moves into or out of folders.",
  "tree": "Displays the directory structure graphically.",
  "move": "Used to move files or rename directories.",
  "path": "Sets the search path for executable files.",
  "prompt": "Customizes the command prompt appearance.",
  "exit": "Closes the MS-DOS command interpreter.",
  "help": "Provides helpful information about DOS commands.",
  "attrib": "Changes file attributes (Read-only, Hidden, etc.).",
  "xcopy": "Extended copy; copies files and directory trees.",
  "fc": "File Compare; compares the contents of two files.",
  "print": "Prints a text file while you are working.",
  "edit": "Opens the built-in MS-DOS text editor.",
  "find": "Searches for a specific string of text in a file.",
  "sort": "Sorts input data in alphabetical or reverse order.",
  "more": "Displays output one screen at a time.",
  "label": "Creates, changes, or deletes a disk volume label.",
  "chkdsk": "Check Disk; checks for errors and shows status.",
  "format": "Formats a disk for use with DOS.",
  "diskcopy": "Copies the entire contents of one floppy disk to another.",
  "fdisk": "Used to configure and partition hard disks.",
  "sys": "Transfers DOS system files to another disk.",
  "scandisk": "A tool to find and fix disk surface and file errors.",
  "defrag": "Defragments files to improve disk performance.",
  "backup": "Creates safety copies of files.",
  "restore": "Recovers files from a backup created by BACKUP.",
  "diskcomp": "Compares the contents of two floppy disks.",
  "echo": "Displays messages or turns command echoing on/off.",
  "pause": "Suspends batch file execution until a key is pressed.",
  "rem": "Used for comments (remarks) in batch files.",
  "call": "Runs one batch file from within another.",
  "shift": "Changes the position of parameters in a batch file.",
  "if": "Performs conditional processing in batch files.",
  "goto": "Directs DOS to a labeled line in a batch file.",
  "for": "Runs a specified command for each file in a set.",
  "set": "Sets or displays environment variables.",
  "mem": "Displays the amount of used and free memory.",
  "net": "A command used for network-related settings.",
  "ping": "Tests the connection between two network nodes.",
  "hostname": "Displays the name of the computer on the network.",
  "doskey": "Recalls DOS commands, edits lines, and creates macros.",
  "append": "Allows programs to open files in specified directories.",
  "subst": "Assigns a drive letter to a specific path.",
  "command.com": "The default command-line interpreter for MS-DOS.",
  "io.sys": "A critical system file that handles hardware communication.",
  "msdos.sys": "A system file that contains the DOS kernel logic.",
  "autoexec.bat": "A batch file that runs automatically at startup.",
  "config.sys": "The main configuration file for DOS system settings.",
  ".bat": "The file extension for DOS batch files.",
  ".exe": "The file extension for executable programs.",
  ".com": "The file extension for small command programs.",
  "cli": "Command Line Interface; text-based user interaction.",
  "gui": "Graphical User Interface; icon-based user interaction.",
  "booting": "The process of starting the computer system.",
  "reboot": "Restarting the computer system.",
  "prompt": "The symbol or text indicating DOS is ready for input.",
  "wildcard": "Special characters (*, ?) used for pattern matching.",
  "*": "A wildcard representing multiple characters.",
  "?": "A wildcard representing a single character.",
  "root": "The primary or main directory of a disk.",
  "path": "The complete address or location of a file.",
  "file": "A collection of related data stored under a name.",
  "directory": "Another word for a folder in the DOS environment.",
  "subdirectory": "A folder located inside another folder.",
  "extension": "The 3-character suffix indicating a file type.",
  "hidden": "An attribute that makes a file invisible in normal DIR lists.",
  "read-only": "An attribute that prevents a file from being modified.",
  "archive": "An attribute used by backup programs to track changes.",
  "system": "An attribute identifying files as critical OS files.",
  "kernel": "The core component of an operating system.",
  "shell": "The user interface part of the operating system.",
  "utility": "Software used for system maintenance and support.",
  "driver": "Software that controls specific hardware components.",
  "ram": "Random Access Memory; temporary workspace memory.",
  "rom": "Read Only Memory; permanent startup memory.",
  "himem.sys": "Manages extended memory above 1 megabyte.",
  "emm386.exe": "Provides access to expanded memory using XMS.",
  "conventional": "The first 640 KB of memory in DOS.",
  "extended": "Memory above the 1 MB limit in PC systems.",
  "expanded": "An older method of adding memory via bank-switching.",
  "batch": "A set of commands executed as a single script.",
  "pipe": "Directs the output of one command into another.",
  "redirection": "Sending data to a file or device instead of the screen.",
  ">": "Operator for output redirection to a file.",
  ">>": "Operator for appending output to an existing file.",
  "<": "Operator for input redirection from a file.",
  "|": "The pipe operator used to link DOS commands.",
  "ctrl+c": "The shortcut to stop a running command.",
  "ctrl+break": "The shortcut to interrupt a system process.",
  "alt+enter": "Toggles full-screen mode for the DOS window.",
  "syntax": "The correct format or grammar for a command.",
  "parameter": "An extra piece of information passed to a command.",
  "argument": "The actual value provided for a parameter.",
  "environment": "The set of variables that define system behavior.",
  "startup": "The initial boot process of the computer.",
  "bootsector": "The specific disk sector used to start the OS.",
  "volume": "The name or label assigned to a disk partition.",
  "fragmentation": "When files are scattered across different disk areas.",
  "defragmentation": "Rearranging disk data to be contiguous and faster.",
  "prompting": "When the system waits for user input.",
  "parsing": "The way DOS analyzes and breaks down a command string.",
  "execution": "The act of running or carrying out a command.",
  "batchprocessing": "Executing a series of commands automatically.",
  "multitasking": "Executing multiple tasks at the same time.",
  "single-user": "A system designed for one person at a time.",
  "single-tasking": "A system that runs only one program at a time.",
  "executable": "A file that can be directly run by the computer.",
  "utilitysoftware": "Software used for system maintenance tasks.",
  "operatingsystem": "Software that manages all hardware and software.",
  "networking": "The process of connecting multiple computer systems.",
  "host": "The primary computer in a network setup.",
  "client": "A computer that requests services from a server.",
  "server": "A computer that provides shared resources or services.",
  "protocol": "A set of rules for communication between devices.",
  "packet": "A small unit of data sent over a network.",
  "buffer": "A temporary storage area for data in transit.",
  "device": "Any hardware component connected to the system.",
  "input": "Data or instructions entered into the computer.",
  "output": "The result or data produced by the computer.",
  "process": "A program currently in the state of execution.",
  "memory": "The area where data is stored for processing.",
  "instruction": "A single operation that the computer can perform.",
  "interpreter": "A program that executes instructions one by one.",
  "internal": "A command that is part of the memory-resident shell.",
  "external": "A command that exists as a separate disk file.",
  "utilitydisk": "A disk containing system maintenance tools.",
  "backupdisk": "A disk used for storing safety copies of data.",
  "startupdisk": "A bootable disk used to start the computer.",
  "volumelabel": "The name given to a disk for identification.",
  "diskdrive": "The hardware device used to read/write disks.",
  "harddisk": "The main permanent storage device of a computer.",
  "floppy": "An older, magnetic-based portable storage disk.",
  "diskette": "Another name for a small floppy disk.",
  "console": "The text-based user interface screen.",
  "commandline": "The line where text commands are typed.",
  "dosprompt": "The specific symbol indicating DOS is ready."
};

// Merge into the global knowledge base
if (typeof BCA_BOT_KNOWLEDGE !== 'undefined') {
  Object.assign(BCA_BOT_KNOWLEDGE, MS_DOS_KNOWLEDGE);
}
